### ISSUE TITLE
No result in people picker if guest filter is enabled

### ISSUE THREAD

**Issue by staehelir** [Yvand/AzureCP#107]
We use SharePoint Foundation 2013 with the newest AzureCP version. We add a second Azure AD to the AzureCP and want to filter out guest accounts. When we enable guest filter, then the people picker can't find any account from the second Azure AD. After disable the guest account filter, then the people picker shows all account from the second Azure AD.

**Comment by NaveenKanukuntla** [comment]
@Yvand : I do have the same issue. I do not seem to get any results if 'filter guest users' is selected when configuring my Azure Connection.

**Comment by Yvand** [comment]
Ok, I was waiting for @staehelir to send more data but it looks like an actual bug, I will repro it soon and let you know the result

**Comment by Yvand** [comment]
I tested with 2 tenants, 1 has ExcludeGuests set to true and the other to false:

```powershell
Add-Type -AssemblyName "AzureCP, Version=1.0.0.0, Culture=neutral, PublicKeyToken=65dc6b5903b51636"
$config = [azurecp.AzureCPConfig]::GetConfiguration("AzureCPConfig")
$config.AzureTenants[0].ExcludeGuests=$true
$config.AzureTenants[1].ExcludeGuests=$false
$config.Update()
```

It all works as expected: guest accounts of AzureTenants[0] are filtered out and both members and guests are shown in AzureTenants[1].
@NaveenKanukuntla @staehelir am I missing something?

**Comment by NaveenKanukuntla** [comment]
@Yvand : I think I now understand what is going wrong.

When we add a Tenant, we have a choice to select 'Filter our Guest Users' on the configuration screen

![image](https://user-images.githubusercontent.com/19915644/100899547-f7f61780-348f-11eb-9896-2440a3a26ab1.png)

So, when I configure like above and perform a search, the below is what I get.

![image](https://user-images.githubusercontent.com/19915644/100899049-69819600-348f-11eb-86ae-75ab1ede3966.png)


![image](https://user-images.githubusercontent.com/19915644/100899382-c5e4b580-348f-11eb-9101-5ef2062a5727.png)

But, when I configure the connection without selecting the 'Filter out Guest users on this tenant' and use PowerShell to update the filter attribute it works.

```
Identifier                  : xxxx
Name                        : xxxx
ApplicationId               : xxxx
ApplicationSecret           : xxxx
ExcludeMembers              : False
ExcludeGuests               : True
ClientCertificatePrivateKey : 
AuthenticationMode          : ClientSecret
GraphService                : 
UserFilter                  : 
GroupFilter                 : 
UserSelect                  : 
GroupSelect                 : 
UpgradedPersistedProperties : {}
```

So, if I do it through UI it does not work, but with PowerShell it does. Now, I do not know if the update made through PowerShell is really working, since I do not have any guest users in my tenant.

Interestingly, that does not reflect on the configuration page, even though it does show in my PowerShell result.
![image](https://user-images.githubusercontent.com/19915644/100900553-f547f200-3490-11eb-93f7-e39d4d744151.png)
![image](https://user-images.githubusercontent.com/19915644/100900906-553e9880-3491-11eb-95d2-a18d610c4728.png)


I will add some guest users and see. But for now, this is what I found out.

**Comment by Yvand** [comment]
@NaveenKanukuntla thank you for the details, it pointed me directly to the problem, it's really a dump issue: I set property ExcludeMembers instead of ExcludeGuests when the option was set in the new AAD tenant dialog...
It's fixed in https://github.com/Yvand/AzureCP/commit/229c14dd8a81d26225b5b9535978bd2278e93b40

**Comment by NaveenKanukuntla** [comment]
Great. Let me know when the latest version is out and I will test it for you.

**Comment by staehelir** [comment]
@Yvand @NaveenKanukuntla thank you. It works over PowerShell!

**Comment by Yvand** [comment]
@NaveenKanukuntla I just published the pre-release, here is the link: https://github.com/Yvand/AzureCP/releases/tag/19.0.20201207.1262
Thanks!

**Comment by vargasfe** [comment]
Hello Yvan,

 

I just installed release 1262 and I am still unable to get AzureAD groups in people picker.

None of the groups: Security, Microsoft 365, Distribution show up in people picker.

 

I’ve uninstalled, installed, reset configuration, etc. and groups are not returned.

 

Please help…

 

Fernando

**Comment by Yvand** [comment]
@vargasfe this bug is for the guest accounts filter, please open a separate issue for your scenario that is different.
Thanks

**Comment by Yvand** [comment]
@NaveenKanukuntla were you able to test the release?

**Comment by NaveenKanukuntla** [comment]
@Yvand : The issue is now resolved with the latest release. Thank you very much.
