### ISSUE TITLE
When 'Return security-enabled groups only' is checked, no results are returned for Groups

### ISSUE THREAD

**Issue by NaveenKanukuntla** [Yvand/AzureCP#109]
When I check for 'Return security-enabled groups only'. No groups are returned. I have some Azure AD Groups and I do have groups that are synchronized from On-Prem Active Directory on my Dev Farm. I did not work either in V16 or V17 as well.

Here is my AzureCP Settings :
![image](https://user-images.githubusercontent.com/19915644/100623193-cf371c00-32ef-11eb-822f-bf3d9e811fd3.png)

Here are my Claims Settings:
![image](https://user-images.githubusercontent.com/19915644/100623324-fe4d8d80-32ef-11eb-936e-10ccecd85d17.png)

Here are my claim types:
http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name <-- Identifier Claim
http://schemas.microsoft.com/ws/2008/06/identity/claims/role

**Comment by Yvand** [comment]
Thank you for reporting this, I will test it soon and let you know if I repro

**Comment by Yvand** [comment]
It's absolutely a bug, fixed in https://github.com/Yvand/AzureCP/commit/5d1f26bbec662521fde8502ba3449c213393cbed
Thank you for reporting it!

**Comment by NaveenKanukuntla** [comment]
@Yvand : I have installed the latest release and the issue is not resolved. I can now search for users and also security groups.

**Comment by Yvand** [comment]
Just to be clear, did you mean that it resolved the issue or not (you typed "not resolved")?

**Comment by NaveenKanukuntla** [comment]
@Yvand : Sorry about my typo. The issue is now resolved.
